#!/usr/bin/env bash

# Compile the sources into out/scripted.
# Requires Bash 4 for globstar.

set -e

mkdir -p out/scripted
cp -R src/resources out/scripted

shopt -s globstar
javac -cp "/Users/dlubarov/lib/lwjgl-2.9.1/jar/*" -d out/scripted **/*.java
