#!/usr/bin/env bash

# Run the compiled code after "./compile".

set -e

cd out/scripted

java -ea \
  -cp ".:/Users/dlubarov/lib/lwjgl-2.9.0/jar/*" \
  -Djava.library.path=/Users/dlubarov/lib/lwjgl-2.9.0/native/macosx \
  rpg.client.Client
